# Generated by Django 4.0.5 on 2022-07-28 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0007_alter_city_name_alter_rubric_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(help_text='Name', max_length=50, verbose_name='Наименование'),
        ),
    ]
