# Generated by Django 4.0.5 on 2022-08-03 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0008_bb_user_alter_bb_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, db_column='content', null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('dt', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата сообщения')),
                ('bb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='bboard.bb', verbose_name='Объявление')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chats_from', to=settings.AUTH_USER_MODEL, verbose_name='От кого')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chats_to', to=settings.AUTH_USER_MODEL, verbose_name='Кому')),
            ],
            options={
                'ordering': ('-dt',),
            },
        ),
    ]
